-- Create form_options table
CREATE TABLE IF NOT EXISTS form_options (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category TEXT NOT NULL, -- 'POSITION', 'SALARY', 'APPLICATION_MEDIUM', 'APPLICATION_FEE'
  label TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  
  -- Add a constraint to ensure valid categories if needed, but keeping it flexible for now
  CONSTRAINT form_options_label_check CHECK (char_length(label) > 0)
);

-- Enable Row Level Security
ALTER TABLE form_options ENABLE ROW LEVEL SECURITY;

-- Create Policies
-- Allow public read access (needed for displaying the form to anyone, though currently form is admin only)
-- Ideally, if the form is behind AdminAuth, we might restricting this. 
-- However, following existing pattern where read is often open or anon key is used.
-- Let's assume AdminAuth protects the UI, so RLS can be permissive for the service role / anon if needed,
-- BUT strictly we only need this for the admin dashboard.
-- Let's allow SELECT for everyone, and INSERT/UPDATE/DELETE only for authenticated users (or anon if we rely on app-level auth).
-- Given current setup seems to rely on anon key for simplicity in previous steps:
CREATE POLICY "Enable read access for all users" ON form_options FOR SELECT USING (true);
CREATE POLICY "Enable insert for all users" ON form_options FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for all users" ON form_options FOR UPDATE USING (true);
CREATE POLICY "Enable delete for all users" ON form_options FOR DELETE USING (true);

-- Seed Data (from existing hardcoded lists)

-- POSITIONS
INSERT INTO form_options (category, label) VALUES
('POSITION', 'Assistant Professor'),
('POSITION', 'Associate Professor'),
('POSITION', 'Professor'),
('POSITION', 'Vice Chancellor'),
('POSITION', 'Registrar'),
('POSITION', 'Deputy Registrar'),
('POSITION', 'Librarian'),
('POSITION', 'Assistant Librarian'),
('POSITION', 'Controller of Examination'),
('POSITION', 'Head of Department'),
('POSITION', 'Principal'),
('POSITION', 'Dean');

-- APPLICATION MEDIUM
INSERT INTO form_options (category, label) VALUES
('APPLICATION_MEDIUM', 'Interested candidates can apply with updated bio-data and relevant documents through Email within 10 days from the date of advertisement.'),
('APPLICATION_MEDIUM', 'Interested and Eligible candidates may apply through Email by sending their resume and other supporting documents immediately');

-- SALARY
INSERT INTO form_options (category, label) VALUES
('SALARY', 'As per norms'),
('SALARY', 'Strictly follows the UGC and CPC norms');

-- APPLICATION FEE
INSERT INTO form_options (category, label) VALUES
('APPLICATION_FEE', 'UR- Rs. 2000/-'),
('APPLICATION_FEE', 'OBC/EWS – Rs. 1000/-'),
('APPLICATION_FEE', 'SC/ST/PwD/Women- Exempted');
